"""One stylesheet, with explicit cascade ownership and no runtime imports."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / '_content' / 'styles'

def build_styles():
    layers = [
        ('legacy', ['legacy-base.css', 'legacy-article.css', 'legacy-bilingual.css']),
        ('design', ['design.css']),
        ('editorial', ['editorial.css']),
    ]
    output = ['/* Generated by _content/build_styles.py. Edit _content/styles/ sources. */',
              '@layer legacy, design, editorial;']
    for layer, files in layers:
        output.append(f'@layer {layer} {{')
        for name in files:
            output.append(f'/* {name} */')
            output.append((SOURCES / name).read_text())
        output.append('}')
    (ROOT / 'site.css').write_text('\n'.join(output) + '\n')

if __name__ == '__main__':
    build_styles()
